
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../third_party/webrtc/api/video/video_codec_type.h

package org.webrtc;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VideoCodecType.VIDEO_CODEC_GENERIC, VideoCodecType.VIDEO_CODEC_VP8,
    VideoCodecType.VIDEO_CODEC_VP9, VideoCodecType.VIDEO_CODEC_AV1, VideoCodecType.VIDEO_CODEC_H264,
    VideoCodecType.VIDEO_CODEC_H265, VideoCodecType.VIDEO_CODEC_MULTIPLEX
})
@Retention(RetentionPolicy.SOURCE)
public @interface VideoCodecType {
  /**
   * Java_cpp_enum.py does not allow ifdef in enum class, so we have to create two version of
   * VideoCodecType here
   */
  int VIDEO_CODEC_GENERIC = 0;
  int VIDEO_CODEC_VP8 = 1;
  int VIDEO_CODEC_VP9 = 2;
  int VIDEO_CODEC_AV1 = 3;
  int VIDEO_CODEC_H264 = 4;
  int VIDEO_CODEC_H265 = 5;
  int VIDEO_CODEC_MULTIPLEX = 6;
}
